const fs = require("fs");
const path = require("path");

// Read .env.local
const envFile = path.resolve(__dirname, ".env.local");
if (!fs.existsSync(envFile)) {
  console.error("❌ .env.local not found. Run ChangeEnv first.");
  process.exit(1);
}

const envVars = {};
fs.readFileSync(envFile, "utf-8")
  .split("\n")
  .forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const [key, ...rest] = trimmed.split("=");
    envVars[key.trim()] = rest.join("=").trim();
  });

const swContent = `importScripts('https://www.gstatic.com/firebasejs/10.0.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.0.0/firebase-messaging-compat.js');

// Auto-generated by GenerateSW.js — do not edit manually
const firebaseConfig = {
  apiKey: "${envVars["NEXT_PUBLIC_API_KEY"]}",
  authDomain: "${envVars["NEXT_PUBLIC_AUTH_DOMAIN"]}",
  projectId: "${envVars["NEXT_PUBLIC_PROJECT_ID"]}",
  storageBucket: "${envVars["NEXT_PUBLIC_STORAGE_BUCKET"]}",
  messagingSenderId: "${envVars["NEXT_PUBLIC_MESSAGING_SENDER_ID"]}",
  appId: "${envVars["NEXT_PUBLIC_APP_ID"]}",
};

firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  console.log('Received background message ', payload);
  const notificationTitle = payload.notification.title;
  const notificationOptions = { body: payload.notification.body };
  self.registration.showNotification(notificationTitle, notificationOptions);
});
`;

const swDest = path.resolve(__dirname, "public/firebase-messaging-sw.js");
fs.writeFileSync(swDest, swContent);
console.log(`✅ Generated 'public/firebase-messaging-sw.js' from .env.local`);
